name: Backend Build Verify

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Verify build
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller --name=Stellaru --exclude-module tkinter --noconfirm main.py
    - name: Check Output
      run: |
        cd backend
        if [ ! -f ./dist/Stellaru/Stellaru.exe]; then
          exit 1
        fi
